version: '3.9'

x-default: &default
  build: .
  volumes:
    - .:/var/www/car-crud-with-piechart
    - bundle_install:/usr/local/bundle
    - node_modules:/var/www/car-crud-with-piechart/node_modules
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_HOST: postgres

services:
  postgres:
    image: postgres:13.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    <<: *default
    command: >
      sh -c "
        rm -rf tmp/pids/server.pid \
        & ./bin/webpack-dev-server \
        & bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - postgres
    tty: true
    stdin_open: true

volumes:
  postgres-data:
  bundle_install:
  node_modules:

